### ISSUE TITLE
Rationale behind the "_get_name_from_args" function in parameter.py

### ISSUE THREAD

**Issue by havanagrawal** [thouska/spotpy#109]
I don't really understand why this function `_get_name_from_args` is needed. It looks like it processes args and keyword args, looking for specific arguments, and returns them, but this is exactly what Python already does for us. For instance, I don't see why the two following cases are different:

```python
class Uniform(Base):
    """
    A specialization of the Base parameter for uniform distributions
    """

    def __init__(self, *args, **kwargs):
        name, low, high, args, kwargs = self._get_name_from_args('low high', *args, **kwargs)
        super(Uniform, self).__init__(name, rnd.uniform, (low, high), *args, **kwargs)
```

and

```python
class Uniform(Base):
    """
    A specialization of the Base parameter for uniform distributions
    """

    def __init__(self, name, low, high, *args, **kwargs):
        super(Uniform, self).__init__(name, rnd.uniform, (low, high), *args, **kwargs)
```

The latter looks easier to understand and makes the arguments the `Uniform` constructor needs very explicit.

Unless there is a specific usage (such as dynamically deciding the distribution and using that, though I couldn't find anything like that in the codebase), I don't see why it should be written like this.

**Comment by thouska** [comment]
@philippkraft could you have a look?

**Comment by philippkraft** [comment]
The basic idea is to ensure backwards compatibility on the one hand and to make it possible to omit the name of the parameter if the parameter is defined on the class level. These three versions of a parameter defintion should be equivalent:

```python
# Classic definition
my_par = Uniform('my_parameter', 0, 10)
# Class style definition (see tutorial_cmf_lumped.py)
my_parameter = Uniform(0, 10)
# Keyword usage
my_par = Uniform(0, 10, name='my_parameter')
```
All versions should lead to a parameter named ``my_parameter``. I will refactor the code and include this rational into the docstring. Any other thoughts?

**Comment by philippkraft** [comment]
One way to avoid the complicated code would be to move the name parameter behind the distribution parameters, but this would change the API and make parameter calls in the classic variant invalid.

**Comment by philippkraft** [comment]
@havanagrawal would you like to have a look at my fork, if the issue is solved for you?

**Comment by philippkraft** [comment]
See #116

**Comment by havanagrawal** [comment]
Looks good to me, I really like how you moved out the logic into a separate class. I see why it is a difficult choice to make, because of the backward compatibility.

Personally, I also prefer using the class style definition of the spot setup file, and so it seems reasonable that we need this functionality.

Cheers 👍

**Comment by philippkraft** [comment]
Added unittests/test_setup_parameters.py to ensure backwards compatibility and extended test_parameters.py

**Comment by philippkraft** [comment]
@havanagrawal would you close this issue if everything is done?

**Comment by havanagrawal** [comment]
Resolved by moving the logic into another class
