### ISSUE TITLE
objectivefunctions hardcoded (e.g. in sce-ua, mcmc)

### ISSUE THREAD

**Issue by gitporst** [thouska/spotpy#11]
Just stumbled upon it, there is surely a reason for it, but I have not seen it yet.

In algorithms\sceua.py line 194 (as well 385, 395 and 404):
```
        for rep,randompar,simulations in self.repeat(param_generator):        
            #Calculate the objective function
            like = spotpy.objectivefunctions.rmse(self.evaluation,simulations)

```
the likelihood/objective function is calculated based on the RMSE. In the MCMC algorithm it is based on logprob. What are the reasons for that?

**Comment by thouska** [comment]
Yepp that is intended. Though it might not be the best idea. You are not the first one stumbling on this one :)
Intention was to give a reliably working version for these algorithms as they will fail with most of the other implemented objective functions. I am open for other suggestions.

**Comment by gitporst** [comment]
well, what i assumed was, that the objective function defined in the model setup was used. 
Of course, this presumes the user defines one that returns a scalar and is compatible with the algorithm and ideally confirms with the Bayesian approach if used.

Maybe it would be an option to set the objective function as an argument to _algorithm. If the argument is not set, it may fall back to default (e.g. logp or RMSE). 
When it is set, the _algorithm class or a subclass may throw a warning to ensure the user is aware of using a custom one. This can be combined with a reminder to test the input to the objectivefunction for possible violations of distribution properties if a Bayesian approach is employed.
It may throw an error if multiple objective functions are set...

**Comment by thouska** [comment]
sounds good. I would like to keep the change in a way, that one set up class can still be used with every algorithm. So could we use the argument during the initialization of the algorithm? E.g. like this:

    sampler=spotpy.algorithms.mcmc(spot_setup,  dbname='RosenMCMC',  dbformat='csv')
    sampler.sample(rep, use_default_objective=True)

Maybe you already ment to use your idea like this?

**Comment by gitporst** [comment]
yeah, that's what I meant, I'll try to commit one in the next days, from Wednesday on I'll be on vacation for three weeks.

**Comment by thouska** [comment]
I think this is solved now.
