### ISSUE TITLE
Add a ListSampler

### ISSUE THREAD

**Issue by philippkraft** [thouska/spotpy#114]
By now, if one likes to reuse already defined parameter sets, either from older runs or created elsewhere, the setup for spotpy needs to be redefined from the random parameters to list parameters. Adding a new sampler ``class ListSampler(_algorithm)``, that ignores the random function of the parameters but uses the existing parameters in a database would simplify that way.

It would be nice to hear your thoughts from the user community on this before I start coding.

**Comment by kbstn** [comment]
i would appreciate your work on this topic. Actually today i was starting to develop some ugly workarrounds for this problem but got stuck in confusion about those new "par." feature ;)

**Comment by thouska** [comment]
Ok, sounds like a nice enhancement. Based on the idea of @philippkraft, I can work on a first draft for this.
Usage would be:
`sampler = spotpy.algorithms.list(spotpy_setup_class,dbname='posterior',dbformat='csv')`
`sampler.sample(100)`

Output would be:
`results = spotpy.analyser.load_csv_results('posterior_list')`

The sampler would take the parameter combinatios from the given database and run the model with the given number a repetitions. If no repetition is given, the whole database is sampled.

**Comment by philippkraft** [comment]
Looks super, but I would still use dbname for output and not for input to stay consistent.

**Comment by thouska** [comment]
Your are right, this is not completly consitent. However, given the time it took me to check this issue again, I think for now it is most consisting to keep it like it is.
