### ISSUE TITLE
KGE objective function errors with return_all=True

### ISSUE THREAD

**Issue by zutn** [thouska/spotpy#125]
Following error is thrown
![grafik](https://user-images.githubusercontent.com/7868527/36598315-0413252e-18ac-11e8-82c1-825b2bfd9861.png)

**Comment by zutn** [comment]
Calibration Algorithm used is Rope

**Comment by havanagrawal** [comment]
Could you also put the code for the objective function you have written in your spot_setup class?

I imagine this error can be resolved if you use something like:

```python
class spot_setup():
    ...

    def objectivefunction(self, evaluation, simulation, *params):
        kge, cc, alpha, beta = spotpy.objectivefunctions.kge(evaluation, simulation, return_all=True)
        # do whatever with cc, alpha, beta
        return kge
```

**Comment by zutn** [comment]
Seems like the mistake was on my side. Sorry about that.
