### ISSUE TITLE
"index error" when using demcz

### ISSUE THREAD

**Issue by gpau** [thouska/spotpy#14]
I am getting an intermittent "index error" when I use the demcz sampler.  Is it something that I can ignore?  Could you explain what needs to be done to avoid this error?  Thanks.

**Comment by thouska** [comment]
If this is happening only sometimes (sometimes = less than 5% of your samples), this is something you can ignore. I had the error befor, but have not find a clear pattern yet, when this is happening. However, the reason for the error is that either the likelihood or the generated parameter set have not the expected length.

**Comment by gpau** [comment]
Yes, it doesn't happen too frequently.  I will ignore the error for now, and wait for the new version of DEMCz.
