### ISSUE TITLE
Strange behaviour in analyser.plot_posterior_parametertrace

### ISSUE THREAD

**Issue by juancastilla** [thouska/spotpy#140]
Hi,

I am getting some strange periodic behaviour when running the plot_posterior_parameter_trace() method (see attached, first parameter). My gut feeling is that it has to do with the sorting of the sampling records (by increasing likelihood)—perhaps the table is also being sorted on the second column (i.e., the first parameter). I get the same behaviour for different algorithms (SCE-UA and DREAM). Just wondering if anyone has come across this?

<img width="956" alt="periodic_parametertrace" src="https://user-images.githubusercontent.com/4906068/37124933-612eb81a-22a5-11e8-9853-6e4d9b8ef0c4.png">

**Comment by thouska** [comment]
Hi, thanks for this bug-reprt! Your gut feeling was indeed correct. There was some sorting going on in the plot_posterior_parameter_trace() method. I uploaded a fix for that. 
Just for the record: Please mind that this plotting method is more suited for a GLUE approach with MonteCarlo or LatinHypercube samplings. It does not return the "real" posterior parameter distribution of DREAM.

**Comment by juancastilla** [comment]
Thanks for the fix Tobias. Yes, I am aware this plotting method is more suitable for a GLUE approach, but it it also helpful to diagnose convergence of other algorithms.
