### ISSUE TITLE
Unit tests are not "clean", i.e. side-effect-free

### ISSUE THREAD

**Issue by havanagrawal** [thouska/spotpy#141]
Some of the unit tests have a side-effect of leaving CSV/DB files in the directories.

Ideally, the tests should clean up these files in a `tearDown` method.

**Comment by thouska** [comment]
Thanks for this bug-report. Indeed, we have to clean up after the sampling! Would be nice, if someone could tackle this issue.

**Comment by havanagrawal** [comment]
I can take this up 😄
