### ISSUE TITLE
demcz error 

### ISSUE THREAD

**Issue by gpau** [thouska/spotpy#15]
I have been getting this error that I don't understand:

/home/gpau/anaconda2/lib/python2.7/site-packages/spotpy/algorithms/demcz.py:428: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return self._combined_history[(np.ceil(self.relevantHistoryStart) *self._nChains):(self.relevantHistoryEnd \* self._nChains),self.group_indicies[name]]
Traceback (most recent call last):
  File "driver_spotpy.py", line 97, in <module>
    sampler.sample(rep,nChains=3,burnIn=0)
  File "/home/gpau/anaconda2/lib/python2.7/site-packages/spotpy/algorithms/demcz.py", line 240, in sample
    proposalVectors = _dream_proposals(currentVectors, history,dimensions, nChains, DEpairs, gamma, .05, eps)
  File "/home/gpau/anaconda2/lib/python2.7/site-packages/spotpy/algorithms/demcz.py", line 549, in _dream_proposals
    chainDifferences =  (np.sum(combined_history[chains[:, 0:DEpairs], :], axis = 1)      - 
IndexError: index 1 is out of bounds for axis 0 with size 0

Any help is appreciated.

**Comment by thouska** [comment]
Is this happening during the sampling, during the first repetition? Might help to play around with the number of DEpairs. Otherwise, I would need to check your setup files. 
I plan to provide a new written and more robust variant of demc in the next weeks. This might solve this problem on the long run.

**Comment by gpau** [comment]
What do you meant by first repetition?  It looks to me like it is happening towards the end of the sampling.  In any case, if you are updating demc soon, I can wait. Thanks.
