### ISSUE TITLE
Improve hydrological signatures.py

### ISSUE THREAD

**Issue by thouska** [thouska/spotpy#151]
The new version of signatures.py covers atm almost all hydroligcal signatures, listed in Table 2 of the publication by [Westerberg and McMillan, HESS, 2015](https://www.hydrol-earth-syst-sci.net/19/3951/2015/hess-19-3951-2015.pdf).

Whats missing is
- RR (Total runoff ratio)
- P_MA (Mean annual precipitation)
- P_SD (Standard deviation of hourly precipitation)
these signatures curently do not fit in the given API, however I think we should include them somehow.

The new version of signatures.py does not work with any timeseries information. Instead it assumes a continous list of values which cover defiened time grid. If gaps exist, they must me filled by the user with "nan" values first.; signatures.py then interpolates the nan values then by linear regression. This is convienint, however, it has to be used with caution in case of larger gaps. I think we have to discuss ways, how we deal with larger gaps (see also comment by @ThibHlln in #146).

What we further need is a unittest, which tests all functions with some observed discharge data and tests if everything works correctly/reproducable. @zutn: Do you think we can use one of your datasets for that?

And last but not least (from my side): I think a short tutorial is needed, how these functions can be used. I would be very glad, if someone wants to help 😃

**Comment by zutn** [comment]
Some additional ones would be nice, as they are also used in the CAMELS dataset. Here are their explanations and calculations:
![grafik](https://user-images.githubusercontent.com/7868527/39051133-11025f0c-44a8-11e8-8ad4-a6dede45cd5f.png)
![grafik](https://user-images.githubusercontent.com/7868527/39051142-171398a2-44a8-11e8-9d78-4d5b110b6876.png)
![grafik](https://user-images.githubusercontent.com/7868527/39051147-1a14c9f4-44a8-11e8-9af4-09f0f8ed3f9d.png)

**Comment by zutn** [comment]
Added zero_q_freq, see https://github.com/thouska/spotpy/pull/154

The other two signatures need additional rainfall data, should they be included or skipped?

**Comment by thouska** [comment]
Cool thanks. And yes, I think we should include also the signatures which need rainfall data.
Maybe we could implement them with a further keyword?
`get_runoff_ratio(data, measurments_per_day, rainfall_data)`

**Comment by zutn** [comment]
But isn't this a bit problematic in regard to the API?
Maybe split the signatures into two groups?  One were the only input needed is streamflow and one were additional inputs are ok as well?

**Comment by zutn** [comment]
When testing the signatures on a wide variety of catchments I noticed that several signatures fail when more than (probably) 50 % of the time the stream considered has a discharge of 0 mm/day. How could this be adressed? As for those streams the e.g. the median is 0, which results in several divide by 0 errors.
I attached the file. Code for reading it in can be found here: 
`https://github.com/zutn/catchment-similarity/blob/master/catchment_sim_by_signatures.py`

[06846500_streamflow_qc.txt](https://github.com/thouska/spotpy/files/1995240/06846500_streamflow_qc.txt)

**Comment by zutn** [comment]
Fixed some parts now but came across the following problem
![grafik](https://user-images.githubusercontent.com/7868527/39927216-d1b0aa6c-5531-11e8-87c5-865ad2608bc0.png)
Which is causes by this stream
[09535100_streamflow_qc.txt](https://github.com/thouska/spotpy/files/1995495/09535100_streamflow_qc.txt)
Any ideas to fix this? @philippkraft  @thouska

**Comment by zutn** [comment]
I now changed the code to the assumption that a discharge of 0 is always considered baseflow.

**Comment by zutn** [comment]
Adressed all low flow issues in https://github.com/thouska/spotpy/pull/159

Someone should take a look at it though to determine if it makes mathmatical sense. 
@thouska @philippkraft

**Comment by ThibHlln** [comment]
There a package in R that developed flow statistics for intermittent rivers https://github.com/mundl/smires, this might be of interest to you @zutn if you have a flow of zero for prolonged durations. I have not looked into it too much, but they also mention that they deal with missing data, so that is something we could find some inspiration from for SPOTPY @thouska , if they go beyond the linear interpolation currently available in our beloved Python package, that is. Smires is similar to another R package that you probably know https://github.com/USGS-R/EflowStats from USGS, but EflowStats requires strictly continuous series of discharge (sigh), and I also think it is only suitable for perennial streams, so not sure if they deal with zero flows. Anyway, I am just mentioning this for your information, if not aware of it already.

By the way, it would be a great addition/complement to the hydrological signatures (some of them are common though) to have in SPOTPY. I am currently using the EflowStats R package because I did not have time to redevelop them in Python, but if I do in the future, I would surely send a pull request to include them in the hydrology branch of SPOTPY!

**Comment by zutn** [comment]
This post is meant to discuss the different possible implementations of the signatures that divide by the median, how they could handle a median with value 0 and the drawbacks:

1) return Nan: would be mathmatically somewhat consistens, but on the cost that desert catchments cannot be properly compared with other catchments

2) return 0: mathmatically not so sound, but would allow comparisons. Has the drawback of a step in the solutions. Also not very useful when e.g. describing the high flow variability

3) use only days with Q > 0 for the median: would allow comparisons, has not step in its solutions, but mean and median are calculated from different sources

4) use only days with Q > 0 for both mean and median: would allow comparison, has no step in solutions, mean and median are calculated from the same sources. Might ignore a large part of the streamflow information. 

5) Divide by the mean when median = 0: would allow comparisons, but has a step in the solutions, also does not make much sense as it would often be simply 1

So right now I would favor method 4, as it seems the most logic too me. Also the rivers in question have usually have very many low flow values as well and only few days with much flow. Thus the result would still reflect their behaviour reasonably well.

**Comment by zutn** [comment]
I asked a question about this problem on research gate:
[](https://www.researchgate.net/post/How_to_handle_a_median_of_0_when_calculating_hydrological_signatures)

In conclusion, one could say that the hydrological signatures that divide by the median are simply not really applicable on ephemeral catchments. However, if you really want to use them, switching the median with the trimean might be a worthwhile approach.
