### ISSUE TITLE
Algorithm: DDS

### ISSUE THREAD

**Issue by philippkraft** [thouska/spotpy#155]
The "Dynamically dimensioned search algorithm for computationally efficient watershed model calibration" algorithm by [Tolson & Shoemaker 2007](https://doi.org/10.1029/2005WR004723), looks like a good candidate for spotpy - especially for cases where a small number of model evaluation is more important than parameter precision. The paper compares SCE-UA with their new DDS algorithm and this comparison has been challanged in a commentary to that paper [Behrangi et al. 2008](https://doi.org/10.1029/2007WR006429) - however the commentary agrees on a faster yet not that exact convergance of the algorithm.

Implementation in R is available on GitHub: https://github.com/bdb67/Dynamically-Dimensioned-Search

**Comment by thouska** [comment]
This is available now (#195) thanks to @bees4ever
