### ISSUE TITLE
Crash after attempted restart with sceua

### ISSUE THREAD

**Issue by TristanHehnen** [thouska/spotpy#158]
Hi Tobias,

I've experienced a crash when trying to restart a SCEUA optimisation. After the restart it performs a couple of simulations and crashes, showing an error for `_alorithm.py`, line 268 "TypeError: zip argument #1 must support iteration". And then shows another error immediately after for line 274 "AttributeError: 'sceua' object has no attribute 'datawriter'".

However, I assume both may be the result of an attempted restart and `dbinit` being set to `False` (line 167). Then the `save` method (line 262) tries to initialise a database but skips over it. 

Could you please take a look at it?

Many thanks!
Tristan

**Comment by TristanHehnen** [comment]
Also, after the restart it shows "ComplexEvo loop #1 in progress...", despite being stopped before in loop 6.

**Comment by thouska** [comment]
Hi @TristanHehnen,
thanks for this bug report. I will try to fix this in the next couple of days.

**Comment by thouska** [comment]
For now, I am pretty sure that the second error you mentioned "ComplexEvo loop nr1 in progress...", despite being stopped in loop 6 before." is just a printing issue.

**Comment by TristanHehnen** [comment]
Hi Tobias,

thank you having a look at it!
I just added the "ComplexEvo..." for the sake of completeness, just in case it might have been connected or the indication for some other issue.

Cheers

**Comment by TristanHehnen** [comment]
@lu-kas and me have a proposal to fix the aforementioned issue, please see pull request.

**Comment by TristanHehnen** [comment]
We corrected an issue introduced by our proposed fix. Please, have a look at pull request #171.

**Comment by thouska** [comment]
Perfect thanks a lot for your contribution, I will merge you fix. Does this solve the issue?

**Comment by TristanHehnen** [comment]
Well, I'm not totally sure if it does, but for now it looks promising. More testing might reveal some more hidden issues.
At least, we were now able to have it restart and append the new information to the original database file.

However, after the optimisation process itself crashes and gets restarted, new data will appended regardless of the actual progress. Thus, the user may end up having partly completed generations within the database that get expanded by the restarted generation. So, some generations might end up being "streched" in terms of produced results, or number of lines in the database (I hope that explaination is kind of understandable...). We use another script to initiate the restart and let it write markers into the database, such that we can keep track of the completed generations and remove the partly completed ones. Maybe it might be interesting to consider this to become baseline spotpy functionality, that a restart will automatically write markers.
Furthermore, specifically for the SCEUA, it might be interesting to provide further means of process termination. For now, if I understand it correctly, spotpy (with SCEUA) can terminate because it reached the threshold defining convergence, exhaust the amount of trails allowed or being stopped forcefully/crash. 
We think it would be good if the user could provide spotpy with another parameter. This would be the amount of generations, again focused on the SCEUA, it shall complete during a single run. Afterwards it would stop gracefully, writing the results to the db, create a breakpoint for restart and terminate. Maybe it could even check for the existance of a specific *.stop file, or something, to trigger the graceful stop at the next suitable opportunity. Of course, the user could restrict the number of trails allowed and expand this amount for each restart, however it would be nicer as proper functionality.
This behaviour would be very useful, when utilising computing resources employing a scheduler and "computing time tokens", for more efficiently using the computing time. 


We have discovered further issues, that seem to arise somewhere in the mix of spotpy, our script framework that we use to control spotpy functionality and the comutational resources we have access to. This makes it a bit tricky to figure out what is what, there. It might be better to discuss this in seperate issues, if actually related to spotpy.

**Comment by TristanHehnen** [comment]
Just a little heads-up: 
It seems that after the first restart was conducted, no new breakpoints are written. Thus, further restarts keep repeating themselves and there is no more progress. 

I'm investigating this issue and come back to you, after I have a better understanding what is going on with it.
