### ISSUE TITLE
type of simulation results different from 1d array

### ISSUE THREAD

**Issue by gitporst** [thouska/spotpy#16]
I am getting an error, when my simulation results, returned by ths simulation method of the spotpy_setup class is different than a 1d array. Currently, it is a pandas dataframe of 6 arbitrarily long time series. Most algorithms raise an error in parts, where the simulation results are prepared to be stored in the database (ram or csv), e.g. where the header for the csv file is created or where simulation result matrices are selected based on the acceptance vector in demcz as an example. Are you interested in extending support for non 1d arrays of simulation results?

**Comment by thouska** [comment]
You are right, all optimization algorithms accept only 1d arrays for the simulation. Would be nice to extend that to nd arrays, makes especially sense if #11 is implemented.

**Comment by gitporst** [comment]
From what I call tell, results of the iterations of optimization are written to database via the save method. The arguments to that call are (objectivefunction,parameterlist,simulations,chains):
like is either a float or a list of floats if multi-objective-function
param is a list of param values or a list thereof if multiple chains
simulation can be anything (normally 1d-array) or a list thereof if multiple chains
chain is an integer or a list of chain indices if multiple chains

If ram is defined, indivual lists are built using append, results are thus stored in memory.
If csv is definded, results are dynamically written to file, and not stored in memory.

I think that saving nd-arrays calls for another method (writing to csv takes too much time, and storing the results in memory may be also very expensive). Probably implementing a custom method would make sense (that is not merged to spotpy). Still, I'll try to figure out a way to outsource all the manipulations on the (objectivefunction,parameterlist,simulations,chains) in the algorithms to the database method.

**Comment by thouska** [comment]
From what I can tell, writting csv files is at least faster than expected, as far as you do not want to save really huge ouputs. I tested it with up to 20,000 values per line, without a significant time loss. And you are right, I guess, storing in memory would only be a good idea for short optimization runs.
 
I believe support for hdf and sql databases would be a very nice feature. However, I did not had the time yet to implemented them. Have you considered to use the interface to a user-defined database (http://fb09-pasig.umwelt.uni-giessen.de/spotpy/Tutorial/6-Advanced_hints/#create-a-own-database)? It takes (objectivefunction,parameterlist,simulations,chains) and the user can do with that whatever he/she wants.

**Comment by NickAlexander18** [comment]
Sorry for pulling this closed issue, but I found the function spot_setup.save can't work when I use the sceua algorithm, this is my code:

`class spotpy_setup(object):`

         def __init__(self):
            self.params = [spotpy.parameter.Uniform("a",8,15,0.1,0.2,8,15),spotpy.parameter.Uniform("b",590,700,0.5,1,590,700), ]   
        
        def parameters(self):
            return spotpy.parameter.generate(self.params)`

        def simulation(self,vector):      
            x=np.array(vector)
            ...some works
            return simulations

        def evaluation(self):
            observations = [4760.]
            return observations
        
        def objectivefunction(self,simulation,evaluation):
            objectivefunction= spotpy.objectivefunctions.rmse(evaluation,simulation)      
            return objectivefunction

        def save(self, objectivefunctions, parameter, simulations, chains=1):
            print(objectivefunctions, parameter, simulations) # this is for testing whether function save  works
    
    sampler=spotpy.algorithms.sceua(spotpy_setup())

    sampler.sample(repetitions=100, ngs=45, kstop=100, peps=0.1, pcento=0.1, max_loop_inc=3000)`
  I didn't set up the dbname and dbformat, why the function save didn't work?

**Comment by thouska** [comment]
Hi @NickAlexander18,
thank you for your message. You need to define dbname and dbformat. So if your adjust the second last line accordingly, it will work:

`sampler = spotpy.algorithms.sceua(spot_setup(), dbname="test", dbformat="csv")`
