### ISSUE TITLE
dtype of "pcento" in the SCEUA algorithm 

### ISSUE THREAD

**Issue by flydream0428** [thouska/spotpy#162]
In the current code,  "pcento" is described as an int variable. My understanding is it is a float. It will be multiplied by 100 in the code to get the percentage. For example, if we want the criterion 10%, we need to assign 0.1 to this input variable. Am I wrong? 
pcento: int 
            the percentage change allowed in kstop loops before convergency

**Comment by thouska** [comment]
Thank you for pointing this out. Indeed you are correct. I uploaded the according change in the doc string.
