### ISSUE TITLE
SOS! random model runs failed for no reasons when DREAM is used 

### ISSUE THREAD

**Issue by flydream0428** [thouska/spotpy#168]
I am trying to use DREAM to do some parameter estimation. Spotpy is used with MODFLOW. The DREAM was selected. In the generated database, I can see many model runs failed. However, if I run MODFLOW outside spotpy with the same parameter set. All models can be run successfully.  Do you have any idea what can go wrong? I have spent two weeks on this without any progress. SOS!

**Comment by thouska** [comment]
Hi @flydream0428 
thanks for your message and sorry for this inconvenience. I think we have to narrow this issue down to the real source of the error. For this you might want to use the list sampler:
`sampler = spotpy.algorithms.list(spotpy_setup_class,dbname='your_dream_dbname',dbformat='csv')`
`sampler.sample(your_nr_of_repetitions)`
 It takes the parameters from your database that you generated with the DREAM sampler and runs your model again. So more or less the same that you already tested, but inside of the SPOTPY framework. If this works, we can narrow it down to the dream algorithm. If not, we have to search somewhere else.

**Comment by flydream0428** [comment]
Thanks a lot, I will have a try
