### ISSUE TITLE
error: package directory 'spotpy\examples\cmf_data' does not exist

### ISSUE THREAD

**Issue by ThibHlln** [thouska/spotpy#173]
Hi Tobias !

There seems to be an issue with the new version of spotpy for python 2.7 on Windows. See, for example:
(https://ci.appveyor.com/project/ThibHlln/smartpy/build/job/9uxbi63r3o60qy44)

I am assuming it is because cmf_data does not have an __init__.py file? So it is not recognised as a subpackage?

The problem does not seem to appear on linux though for some reason.

Hope this helps.

**Comment by thouska** [comment]
Hi Thibault,
thank you very much for you super fast bug report. I added the missing __init__.py file and uploaded a new version on pypi. I also think this should fix the error. However, it would be very nice if you would let me know, if the error persists.

**Comment by ThibHlln** [comment]
No worries. I am glad if this helped.

Yes, it was very quick because I am using spotpy for the monte carlo simulations with my model (https://github.com/ThibHlln/smartpy), so the continuous integration service I am using made me aware of the issue because my project was failing. :-)

Everything seems to be alright with the latest version of spotpy: https://ci.appveyor.com/project/ThibHlln/smartpy

You are probably aware of it, but AppVeyor provides a CI service on Windows virtual machines, so, if you would like, you could re-use the unittests you already have to test spotpy in a Windows environment. AppVeyor is a bit slow compared to Travis CI, but it does the job and it is free for open source projects.
