### ISSUE TITLE
Error with Sampler: "Evaluation() missing 1 positional argument: self"

### ISSUE THREAD

**Issue by eesmero** [thouska/spotpy#181]
Hello,

I've been attempting to incorporate the GR4J hydrological model into Spotpy in order to use SCE-UA to optimise the parameters however the title error keeps popping up.

Here is the full error:

Traceback (most recent call last):
  File "C:/Users/elija/PycharmProjects/Riveract/Model/test2.py", line 147, in <module>
    sampler = spotpy.algorithms.mc(Setup, dbname='scuea_gr4j', dbformat='csv')
  File "C:\Users\elija\AppData\Local\Programs\Python\Python37\lib\site-packages\spotpy\algorithms\mc.py", line 54, in __init__
    super(mc, self).__init__(*args, **kwargs)
  File "C:\Users\elija\AppData\Local\Programs\Python\Python37\lib\site-packages\spotpy\algorithms\_algorithm.py", line 160, in __init__
    self.evaluation = self.setup.evaluation()
TypeError: evaluation() missing 1 required positional argument: 'self'

Would you be able to help me? I have attached the necessary files.

[GR4J Spotpy.zip](https://github.com/thouska/spotpy/files/2382874/GR4J.Spotpy.zip)

**Comment by eesmero** [comment]
Thanks for such a quick reply! I downloaded it straight from the PyCharm Interpreter which says the repository is from pypi.python.org. Should I try the GitHub version?

**Comment by thouska** [comment]
Ok, I just tested your code with the current GitHub version and got the same error message. I will look into that and keep you updated.

**Comment by thouska** [comment]
Ok, I found the reason for the error meassge: Have a look in Line 147 of your code. You should always initialize your spot_setup class before transferring it to the sampler, i.e. just change it to:
`sampler = spotpy.algorithms.sceua(Setup(), dbname='scuea_gr4j', dbformat='csv')`
I have to admit that the error message is a bit misleading, sorry for that.

**Comment by eesmero** [comment]
Oh wow just a "()" made a difference haha. Thanks so much for the help! Appreciate it

**Comment by thouska** [comment]
Your welcome, good look with your research!
