### ISSUE TITLE
FAST algorithm not computing first or total order correctly

### ISSUE THREAD

**Issue by tnigon** [thouska/spotpy#184]
The FAST algorithm is returning a value of 1.0 for each params variable (see below). I have 7 params I am checking, and 5 outputs. I only ran 70 simulations, so perhaps I may need to run more. If so, it may be good to check for an approximate minimum number of simulations prior to running FAST. And if not, any idea what I could check to troubleshoot this? There is a divide by zero RuntimeWarning when calculating <omega> in fast.py.

Thanks,

Tyler

> Best run at 48 of 70 (best like=-39.04) with parameter set:
[   7.26253773    0.89667655  187.52178456   89.71978214    0.90117337
    3.68778443    3.79185629]
Duration:860.46 s
70
Parameter First Total
DRT 1.000000 1.000000
FFC 1.000000 1.000000
GWMX 1.000000 1.000000
GWST 1.000000 1.000000
ST 1.000000 1.000000
WTBL 1.000000 1.000000
WTMX 1.000000 1.000000
C:\Anaconda3\lib\site-packages\spotpy\algorithms\fast.py:164: RuntimeWarning: divide by zero encountered in remainder
  omega[1:] = np.arange(D - 1) % m + 1

**Comment by tnigon** [comment]
I just saw more information on the Advanced hints page - sorry about not reading over more thoroughly beforehand. Still, it would be great to do this calculation on N prior to running the model.

Tyler

![image](https://user-images.githubusercontent.com/8249296/45773324-a09d6100-bc0f-11e8-9776-6ce83ab9344d.png)

**Comment by thouska** [comment]
Hi @tnigon 
thanks for your message and very nice that you solved this issue by yourself :)
I am confident that you get better results with a robust setting of the repetitions.

I will pick up your recommendation and provide an short tutorial for every algorithm in due time. 
However, as the equation by Henkel et al (2012) is only a guidance and not a fixed rule, I would like to keep the freedom to the users to decide, what they want to do.

**Comment by tnigon** [comment]
@thouska,

In my version of spotpy, I changed the sample() function to include the following just as a warning to the user that there may not have been enough iterations. I tried a pull request, but I do not have permissions.

Please feel free to implement if you'd like.

Thanks,

Tyler

`    def sample(self, repetitions, M=4, d=2):
        """
        Samples from the FAST algorithm.

        Input
        ----------
        repetitions: int 
            Maximum number of runs.  
        """
        print('Starting the FAST algotrithm with '+str(repetitions)+ ' repetitions...')
        self.set_repetiton(repetitions)
        print('Creating FAST Matrix')
        # Get the names of the parameters to analyse
        names = self.parameter()['name']
        # Count the minimum numper of reps required (Henkel et al. (2012)))
        k = len(names)
        min_iters = (1 + (4*(M**2)*(1 + (k - 2)*d)))*k
        if repetitions < min_iters:
            print('\nWARNING: the number of repetitions is less than the minimum required for computation.')
            print('Reps: ' + str(repetitions))
            print('Minimum iterations required: ' + str(min_iters) + '\n')`
