### ISSUE TITLE
optguess and step

### ISSUE THREAD

**Issue by gitporst** [thouska/spotpy#19]
how and when do the optguess and step attributes come into play?

**Comment by thouska** [comment]
optguess comes for the simulated annealing (sa) algorithm into play, as it gives the starting point for this algorithm. It was also implemented for mle and mcmc, but became obsolet, after I implemented a burn-in phase for these algorithms.

step comes into play for mle, mcmc and sa and defines, how far the algorithm can jump away from a current parameter setting, given as the standard derivation of a gaussian distribution, with the current parameter settung as mean value:

     new_par.append(np.random.normal(loc=old_par[i], scale=stepsizes[i]))

**Comment by gitporst** [comment]
Ah, okay. Would it be a good idea, if the optguess attribute influenced all algorithms in that it is used as a starting point (in one chain, if multi-chain approach)? Although this probably then should only be the default behaviour, if optguess is externally given as an argument when initializing the parameter distribution...

**Comment by thouska** [comment]
yepp, this would be the consequent implementation. Though, I do not know if it is possbile to implement this into _algorithm.py. Would require some work for every algorithm.

**Comment by philippkraft** [comment]
One extra meaning for optguess: works now as a default value in spotpy.parameter.create_set, if random=False.
