### ISSUE TITLE
MemoryError when optimising 10 years worth of data with DECMz algorithm

### ISSUE THREAD

**Issue by eesmero** [thouska/spotpy#192]
Hello,

I am unable to run an optimisation for 144571 rows of data using the DECMz due to a MemoryError. I have attached the trace.

> C:\Users\elija\AppData\Local\Programs\Python\Python37\python.exe C:/Users/elija/PycharmProjects/Riveract/Model/parameteroptimisation.py
> Starting the DEMCz algotrithm with 1 repetitions...
> Traceback (most recent call last):
>   File "C:\Users\elija\AppData\Local\Programs\Python\Python37\lib\site-packages\spotpy\algorithms\_algorithm.py", line 325, in getfitness
>     return self.objectivefunction(evaluation=self.evaluation, simulation=simulation, params = (params,self.parnames))
> TypeError: log_p() got an unexpected keyword argument 'params'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/elija/PycharmProjects/Riveract/Model/parameteroptimisation.py", line 31, in <module>
>     sampler.sample(1)
>   File "C:\Users\elija\AppData\Local\Programs\Python\Python37\lib\site-packages\spotpy\algorithms\demcz.py", line 201, in sample
>     likelist = self.postprocessing(i, list(vector), simulations, chains=rep)
>   File "C:\Users\elija\AppData\Local\Programs\Python\Python37\lib\site-packages\spotpy\algorithms\_algorithm.py", line 302, in postprocessing
>     like = self.getfitness(simulation=simulation, params=randompar)
>   File "C:\Users\elija\AppData\Local\Programs\Python\Python37\lib\site-packages\spotpy\algorithms\_algorithm.py", line 329, in getfitness
>     return self.objectivefunction(evaluation=self.evaluation, simulation=simulation)
>   File "C:\Users\elija\AppData\Local\Programs\Python\Python37\lib\site-packages\spotpy\objectivefunctions.py", line 151, in log_p
>     y = (np.array(evaluation) - np.array(simulation)) / scale
> MemoryError
> 
> Process finished with exit code 1

I have also attached the relevant files. Please change the references of the input data 3.1 file in the 2 .py files then run the parameteroptimisation.py code.

[Spotpy Issues.zip](https://github.com/thouska/spotpy/files/2472242/Spotpy.Issues.zip)

Cheers,
Elijah

**Comment by thouska** [comment]
Hi,
just change line 21 in your parameteroptimization script to:
observations = list(input_data.iloc[:, 2])

**Comment by eesmero** [comment]
Hi thouska,

That worked, thanks heaps!
