### ISSUE TITLE
Issue with SCEUA/MPI

### ISSUE THREAD

**Issue by Patrick-Lauer** [thouska/spotpy#2]
Dear spotpy team,

I've encountered an issue with the MPI implementation in SpotPy using the SCEUA algorithm. As you can see in the attached files, the value of the objective function seems not to be handled correctly after the burn in phase. When the complex evolution starts in parallel mode, the value of the objective function isn't updated anymore in the status function but correctly written to the database. This leads to a situation, where the algorithm can't work correctly and acts as some kind of mc algorithm. However, the serial version works completely as it is intended.

I've attached a few files to  illustrate the issue. There is a rosenbrock optimization problem just like you offer in the spotpy sample folder. It's calculated twice, once in serial mode and once in mpi mode. As you can see in the out file, in the mpi version, the value of the objective function in the status function isn't updated any more after the burn in phase (nopt=2, ngs=24, npt=120). Anyway, the correct value is written to the csv file. Please also note the x_y_trace files. The serial version reaches convergence after about 7200 trials, the mpi version converges after 77000 trials. I even run some test cases where convergence was never reached in mpi mode.

Kind regards

Patrick

[sceua_mpi.zip](https://github.com/thouska/spotpy/files/136758/sceua_mpi.zip)

MPI version:
![x_y__trace_mpi](https://cloud.githubusercontent.com/assets/13256462/13154372/ed92f7f6-d678-11e5-9319-dc99d1146155.png)
Serial version:
![x_y__trace_serial](https://cloud.githubusercontent.com/assets/13256462/13154373/ed937b72-d678-11e5-971b-36cd0a5cea0e.png)

**Comment by thouska** [comment]
Hello Patrick,

thank you for your bug report. This behaviour of the SCE-UA algorithm was indeed not intended. After some searching, I think I found the reason for the wrong functionality. The latest version of SPOTPY (**>=1.2.5**) should fix the bug. Please let me know, if the new version works correctly.

Kind regards,
Tobias

**Comment by Patrick-Lauer** [comment]
Dear Tobias,

thank you for your quick response. As long as I can tell, I think now the algorithm itself works correctly. But there is still a bug in the progress bar, that is connected to this former bug, in my view.

            #Progress bar
            acttime=time.time()
            if acttime-intervaltime>=2:
                text='%i of %i (best like=%g)' % (rep,repetitions,self.status.objectivefunction)
                print(text)
                intervaltime=time.time()

If the code is run in parallel mode, printing self.status.objectivefunction still just gives you the best like value from the burn in phase, even if the algorithm itself works as intended. In serial mode, the value is updated and printed as expected with converging to a solution.

Kind regards

Patrick

**Comment by thouska** [comment]
Hey Patrick,

thanks again for this report. You are right, there was another minor bug during the collection of the so far best found parameter set and objective function. The calculation itself should not have been affected by this. I have uploaded a new version (1.2.6) with the corresponding bugfix.

Kind regards,
Tobias

**Comment by Patrick-Lauer** [comment]
Hey Tobias,

sorry, couldn't test it before. With 1.2.6 now this bug also is solved. Thank you. I may click the "close" button.

Kind regards

Patrick
