### ISSUE TITLE
SCE-UA and CSV, not all results of a generation are written at once

### ISSUE THREAD

**Issue by TristanHehnen** [thouska/spotpy#207]
Hi!

I'm experiencing an issue where not the full parameter sets of a completed generation are written to a file, when the CSV database option is used. About a complex worth of parameter sets seems to be "held back" for the first generation conducted. The following generations appear to be complete, however shifted by a "complex". I've explicitly checked one "dump cycle" in which a full generation was written. It may be different with others, however the amount of remaining parameter sets needed for completion seem to be consistant for which I assume this behaviour also extents to cases which I've not explicitly looked at.
The tricky thing with this is that now two generations need to be completed for one to be fully written. 
I'm wondering if this is related to the routine responsible for saving the data or if is on my end. Has someone seen similar behaviour? Am I missing/overlooking something?

Cheers.

**PS:**
I've performed a quick test with two restarts, "residue" means how many parameter sets would need to be written to complete the last generation:

Complex size: 73
Generation size: 2628
Number of restarts: 2

**Restart: 0**
Individuals: 10441
Residue: 71

**Restart: 1**
Individuals: 5185
Residue: 71

**Restart: 2**
Individuals: 5184
Residue: 72

**Parameter sets written during a "dump cycle":**
18183 propti_db.csv
20811 propti_db.csv
Difference: 2628

**Comment by thouska** [comment]
Hi Tristan,
thank you for your message and this detailed problem description. How did you generate this “dump cycle”, i.e. whats the difference to the csv saving?
Just for the SCE-UA algorithm is [designed to return not all model runs](https://github.com/thouska/spotpy/blob/master/spotpy/algorithms/sceua.py#L384-L410). So during the optimization the algorithm tests different parameter sets with the model (up to 3 parameter sets which are generated in a different way). If a parameter set failed to be better than a previous one, the results are not saved (by design of the algorithm). However, to allow a fair comparison to other algorithms. I decided to count these failed tests as a repetition within SPOTPY , as the model has been started. However, given the design of the algorithm, the results are not saved in the database. So the behavior for all implemented databases.

**Comment by TristanHehnen** [comment]
Hi Tobias,
thanks for the fast reply!

The "dump-cycle" is nothing that I (deliberately) set up, but rather me labeling a behaviour that I've observed. 

As general behaviour of the SCE, I see that all parameter sets of generation 0, the burn-in, are written in fast succession and continuously to the CSV file. The following generations run for hours, in my case, without anything being written to the file. Then, at some point chunks of data, presumably finished complexes, are written - the "dump-cycle". So, it basically should be the original CSV saving procedure, as implemented in SPOTPY; at least this is how I was intending to use it.

**Trying to clarify things:**
Even though not all actually computed parameter sets are saved / written to disk, there is still a pattern in the data which I understood to be the "generations". When plotting "like" against "repetition" as scatter plot, there are clearly visible "steps", or "generations". The amount of data points is equal to `npt`, which I understood as "generation". For my specific setup, I'm using 36 parameters and an equal number of complexes (`nopt`=36, `ngs`=36 --> `npg`=73, `npt`= `ngs`*`npg`=2628). See the figure below as an example:
![FitnessScatter](https://user-images.githubusercontent.com/34650649/54825657-60966400-4cae-11e9-9330-91d3a21cc3a7.png)

After generation 0, all data is written to the file, as explained above. Now, for generation 1, less than `npt` parameter sets are written, about `npg` are missing but not quite (see first post). The remaining ones are written after generation 2 is finished and here the total amount of data equals `npt`. Since the start (generation 1) missed some entries, the dump after generation 2 is not the complete generation 2, just an amount of data worth a generation (`npt`) but shifted by what I called "residue" in the first post. 
_Therefore, I believe this does not originate from to the code you pointed at in your response._
I understand your response as follows: For each generation  `npt` + _x_ parameter sets are generated, where _x_ is up to 3 per parameter set, and evaluated, but only `npt` amount of parameter sets are kept and written to the file.

I hope this makes it a bit clearer.

PS:

Maybe I should rather speak of "lines" instead of "parameter sets", here. However, what I mean is the data that is written, as a new line, to the database file (like1, par*, simulation*, chain).

**Comment by lesliedolce** [comment]
trying to solve the SCE-UA et cvs file.
For my own need, I modifiy the class _RunStatistic and Algorithm to keep track of the best and worst simulation. In The function final_call  I save the simulation and objective min and max
class _RunStatistic(object):
def __init__(self, repetitions, algorithm_name, optimization_direction, parnames):
        self.optimization_direction = optimization_direction #grid, mazimize, minimize
        print('Initializing the ',algorithm_name,' with ',repetitions,' repetitions')
        if optimization_direction == 'minimize':
            self.compare = self.minimizer
            print('The objective function will be minimized')
        if optimization_direction == 'maximize':
            self.compare = self.maximizer
            print('The objective function will be minimized')
        if optimization_direction == 'grid':
            self.compare = self.grid    

        self.rep = 0
        self.parnames = parnames
        self.parameters= len(parnames)
        self.params_min = [np.nan]*self.parameters
        self.params_max = [np.nan]*self.parameters
        self.objectivefunction_min = 1e308
        self.objectivefunction_max = -1e308
        self.starttime = time.time()
        self.last_print = time.time()
        # ldLD
        self.simulation = pd.Series([])
        self.repetitions = repetitions
        self.stop = False

class _algorithm(object):
 def final_call(self):
        self.repeat.terminate()
        try:  
            self.save(self.status.objectivefunction_min, self.status.params_min, self.status.simulation_min, chains=0)
            self.save(self.status.objectivefunction_max, self.status.params_max, self.status.simulation_max, chains=0)
            
            self.datawriter.finalize()
        except AttributeError:  # Happens if no database was assigned
            pass
        self.status.print_status_final()

Here is the modified file
[_algorithm - Copie.py.txt](https://github.com/thouska/spotpy/files/3249220/_algorithm.-.Copie.py.txt)

**Comment by TristanHehnen** [comment]
Hi, I've found an error in my post processing scripts, thus this issue is totally on my end and **not** spotpy.
My apologies.

In my view this issue could be closed now.

**Comment by thouska** [comment]
Hi @TristanHehnen 
nice, thanks for the update! I am glad that this is working fine :)
