### ISSUE TITLE
setup.py does not install database package

### ISSUE THREAD

**Issue by KittelC** [thouska/spotpy#208]
Hello! 

I updates my spotpy package yesterday and realized version 1.4.5 does not install properly - the issue appears to be that the database folder is not loaded with the packages line 16 in the setup.py file.

Cheers!

**Comment by thouska** [comment]
Hi Cecile,

thank you for reporting this bug! I added the folder in line 16 of the setup.py as you correctly proposed. I added the new corresponding version is available on pypi (1.4.6).
