### ISSUE TITLE
When positive RMSE is used for SCE-UA, spotpy is trying to maximise it 

### ISSUE THREAD

**Issue by flydream0428** [thouska/spotpy#211]
###############
When the rmse is used with sce-ua, the screen feedback is trying to favor the high rmse. I checked the output database file. The output looks fine for me, it's coverging to minimize rmse. However, the screen feedback is doing somehting different. 
#################
Defiend objective function:
        def objectivefunction(self,simulation,evaluation):
            like = spotpy.objectivefunctions.rmse(evaluation,simulation) #
            return like
#################
Sampler:
    sampler = spotpy.algorithms.sceua(spotpy_setup, dbname='SCEUA_TR_nwt_log_v2', dbformat='csv', alt_objfun=None, parallel='mpi')
#######################
Screen feedback 
* Database file 'SCEUA_TR_nwt_log_v2.csv' created.
2 of 5000 (best like=4.20488) est. time remaining: 19:28:16
3 of 5000 (best like=7.82415) est. time remaining: 10:09:17
4 of 5000 (best like=9.11453) est. time remaining: 03:55:33
6 of 5000 (best like=9.11453) est. time remaining: 21:19:06
16 of 5000 (best like=9.11453) est. time remaining: 00:22:21
17 of 5000 (best like=10.3767) est. time remaining: 23:14:48
18 of 5000 (best like=10.3767) est. time remaining: 22:33:41
19 of 5000 (best like=10.3767) est. time remaining: 01:41:30
20 of 5000 (best like=10.3767) est. time remaining: 02:20:16
22 of 5000 (best like=10.3767) est. time remaining: 00:27:41
24 of 5000 (best like=10.3767) est. time remaining: 22:52:04
25 of 5000 (best like=10.3767) est. time remaining: 00:33:59
26 of 5000 (best like=11.1997) est. time remaining: 01:01:29
28 of 5000 (best like=11.1997) est. time remaining: 00:06:06
41 of 5000 (best like=11.1997) est. time remaining: 23:03:14
42 of 5000 (best like=11.1997) est. time remaining: 23:23:23
44 of 5000 (best like=18.8545) est. time remaining: 22:49:17
45 of 5000 (best like=18.8545) est. time remaining: 23:06:21
46 of 5000 (best like=18.8545) est. time remaining: 22:54:07

**Comment by thouska** [comment]
Hi @flydream0428 
Thanks for reporting this issue. As you already mentioned, this was only a printing related issue, which should be fixed with [version >=1.5.0](https://pypi.org/project/spotpy/).
Feel free to re-open this issue in case of any problems.

**Please note:** the "alt_objfun=None" keyword is not necessary any more. Spotpy is using the user defined `def objectivefunction` now in any case.
