### ISSUE TITLE
Difference in the optimal criterion at the end of the simulation and the csv file

### ISSUE THREAD

**Issue by lesliedolce** [thouska/spotpy#212]
*** OPTIMIZATION SEARCH TERMINATED BECAUSE THE LIMIT
ON THE MAXIMUM NUMBER OF TRIALS 
10000
HAS BEEN EXCEEDED.
SEARCH WAS STOPPED AT TRIAL NUMBER: 10024
NORMALIZED GEOMETRIC RANGE = 0.896998
THE BEST POINT HAS IMPROVED IN LAST 100 LOOPS BY 100000.000000 PERCENT
End of sampling
Best run at 7238 of 10000 **(best like=0.787619)** with parameter set:
[3.22288767e+02 9.86654814e-01 5.91360201e-01 3.17992685e-03
 5.42097289e-01]
Duration:68.37 s
-------------------------------------------------------------------------------------------
**At the end the simulation 0.7876**
  sampler=spotpy.algorithms.sceua(spot_setup, dbname='SCEUA_hymod', dbformat='csv', alt_objfun=None)
    
 #Start the sampler, one can specify ngs, kstop, peps and pcento id desired
  sampler.sample(rep) 
    
 # Load the results gained with the sceua sampler, stored in SCEUA_hymod.csv
 #results = spotpy.analyser.load_hdf5_results('SCEUA_hymod')
    results = spotpy.analyser.load_csv_results('SCEUA_hymod')
    print(results['like1'].max())

    print((len(results)))

from the csv file:  print(results['like1'].max())    0.7637.  This is what is exactly  stored in the csv file

I had this problem with my own simulation and with the hymod example

May be I am doing something wrong. This is the first time I used this package

Values from the csv file
like1
--
0.7637
0.758
0.7534
0.7305
0.7236
0.723
0.707
0.688
0.6865
0.681
0.675
0.674

**Comment by lesliedolce** [comment]
This file is too big. I put it  in the link
https://drive.google.com/file/d/1BsZw7xrCQagE7bkYRm79tD1unednWyM1/view?usp=sharing

Thanks

**Comment by felipesaam** [comment]
I have the same issue with another model. CSV file is not saving all runs, and the parameter set of the last message show last run's parameters set not the best one.

**Comment by thouska** [comment]
Hi @lesliedolce and @felipesaam 
thank you for reporting this issue. Indeed, the status printing was runinning in the wrong direction. However, this was not affecting the sce-ua results. 
I uploaded a fix for that in a [branch](https://github.com/thouska/spotpy/tree/New-design-for-status-tracking/spotpy). Maybe you want to test it. I will inform you here as soon as I merge the branch and upload a new SPOTPY version on pypi. 

That not all results are saved is intended. It is due to the original version of the SCE-UA algorithm (which was first published as matlab code). Spotpy is desgined to reproduce the results of this original published code.

**Comment by lesliedolce** [comment]
Thank you. I am waiting for the fix to install the new version

**Comment by lesliedolce** [comment]
I would like to test the fix. I cannot see which files have been modified if any.

**Comment by thouska** [comment]
Would be super nice, if you could test it, before I merge the changes on the master branch. I generated a [Pull request](https://github.com/thouska/spotpy/pull/216/files), which allows you to review the changes.
If you want to test this, you can simply clone the [branch](https://github.com/thouska/spotpy/tree/New-design-for-status-tracking) and add the package to your Python libraries.

**Comment by lesliedolce** [comment]
Ok I will do that

**Comment by lesliedolce** [comment]
*** Final SPOTPY summary ***
Total Duration: 34.05 seconds
Total Repetitions: 5039
Minimal objective value: 7.52435
Corresponding parameter setting:
cmax: 194.244
bexp: 0.10844
alpha: 0.454309
Ks: 0.0466951
Kq: 0.524387
******************************
CVS file SCEUA_hymod.csv

like1 | parcmax | parbexp | paralpha | parKs | parKq
-- | -- | -- | -- | -- | --
7.523 | 194.2 | 0.10846 | 0.4543 | 0.0467 | 0.5244

I  created a virtual environment tested with the hymod example within the package, The results seem correct to me.

**Comment by thouska** [comment]
Nice, thanks a lot for the test, I will merge the fix. New version is 1.5.0, which will also be available on pypi in a few minutes.

**Comment by lesliedolce** [comment]
Thanks for this great toolbox
