### ISSUE TITLE
Error with Python 2

### ISSUE THREAD

**Issue by hpsone** [thouska/spotpy#223]
Dear thouska,
In spotpy version 1.5.1 installed from PyPl, there is an error with "ImportError: No module named queue" in "_algorithms.py" although it is correct in github files. Thank you.
Best Regards,
Htun

**Comment by thouska** [comment]
Thanks for your message. I uploaded the current github version on pypi (1.5.2)

**Comment by hpsone** [comment]
> Thanks for your message. I uploaded the current github version on pypi (1.5.2)
Thank you so much for the update. It works very fine. Sorry for late reply as the email went to Forum tab and I am not familiar with GitHub.

Best Regards,
Htun
