### ISSUE TITLE
Changlog and GitHub releases

### ISSUE THREAD

**Issue by MuellerSeb** [thouska/spotpy#225]
Hey there,

just a hint from my side. It would be nice, if the PyPI releases would be triggered by GitHub releases. Sometimes things break due to backward incompatibility and it would be nice to see if there was a new release here and what are the changes.

Since you apparently got a CI via travis this would mean almost no work.

Have a look at a setup of one of my packages:
https://github.com/GeoStat-Framework/ogs5py/blob/master/.travis.yml

It will create wheels with all commits and send them to test.pypi. On a GitHub-tag it will send them to PyPI. The setup uses the package [cibuildwheel](https://github.com/joerick/cibuildwheel).

Also you could easily integrate Zenodo, to get a DOI for each GitHub release. It would be nice to be able to cite a certain version of the code.

Keep up the good work!
Sebastian

**Comment by MuellerSeb** [comment]
Oh I forgot the anniversary of this issue! ;-)

This is still important in my opinion, since we don't have a chance as users to track what changes were made at which point in the git-history.

**Comment by MuellerSeb** [comment]
Now, only the Changelog is missing ;-)

**Comment by thouska** [comment]
Sorry for taking so long to work on this issue. You are right, it was indeed an important one! Thanks for the hint!
I included 
- Pypi releases based on Travis
- Zenodo DOI (will be automatically generated with next release)
- Changelog.md (so far manually written, [conventional-changelog/standard-version](https://github.com/conventional-changelog/standard-version) might be suitable to do this automatically in the future

**Comment by thouska** [comment]
Ok cool, this seems to work now. Thanks again for your hint :)
