### ISSUE TITLE
Documentation page down

### ISSUE THREAD

**Issue by MuellerSeb** [thouska/spotpy#243]
Hey there! Hope you're doing well.

I was wondering, if it could be possible to bring the documentation online again?
Maybe it would be nice to use readthedocs.org at this point. This could be combined with #225

Cheers folks,
Sebastian

**Comment by MuellerSeb** [comment]
Related #238

**Comment by thouska** [comment]
Hi Seb,
glad to hear from you, thats indeed about time. How about this version:
https://spotpy.readthedocs.io/en/latest/

**Comment by MuellerSeb** [comment]
Nice :+1:

**Comment by thouska** [comment]
Ok, I think I updated all the references. Thanks again for pushing this :)
