### ISSUE TITLE
likelihoods.py, generalizedLikelihoodFunction, Line 530 - np.mean should be np.exp

### ISSUE THREAD

**Issue by jds485** [thouska/spotpy#245]
According to the cited paper, Line 530 of likelihoods.py should be 
`mu_t = np.exp(muh * comparedata)`
instead of
`mu_t = np.mean(muh * comparedata)`

**Comment by thouska** [comment]
Hi @jds485 
thank you for double checking this one! Your fix is indeed correct. I uploaded your fix in a new version here on Github and on PyPi (>=1.5.10).
