### ISSUE TITLE
Package dependency scipy

### ISSUE THREAD

**Issue by cpwnd** [thouska/spotpy#249]
The setupy.py can define package dependencies, which are automatically downloaded when installing spotpy.
 See documentation [1]

```python
from setuptools import setup

setup(...
      install_requires=[
          'scipy',
      ],
      ...)
```

Scipy was the first I could think of, because it was missing when I ran spotpy the first time.
Maybe there are more.

[1]: https://python-packaging.readthedocs.io/en/latest/dependencies.html

**Comment by thouska** [comment]
Thx for the Tip, its implemented now with version >=1.5.13
