### ISSUE TITLE
pip can't install spotpy 1.5.11

### ISSUE THREAD

**Issue by MuellerSeb** [thouska/spotpy#256]
# Problem
Can't install recent version of spotpy
```bash
pip install spotpy==1.5.11
```
Output
```bash
ERROR: No matching distribution found for spotpy==1.5.11
```

# Reason
There is only an `.egg` file on pypi:
https://pypi.org/project/spotpy/1.5.11/#files

# Solution
When uploading artifacts to pypi, there should be a `py3-none-any.whl` and a source distribution.

**Comment by thouska** [comment]
Hi @MuellerSeb,
thanks for this super fast test, i will try to fix this asap

**Comment by MuellerSeb** [comment]
You could have a look at one of my travis configs:
https://github.com/GeoStat-Framework/ogs5py/blob/master/.travis.yml

I don't use the deploy mechanism of travis, but instead I create a deploy stage, where every commit has a test-deploy to test.pypi.org ... on tag/release, it is also deployed to pypi.org, but you can check the deployment for previous commits on test.pypi.org

I also use [setuptools_scm](https://github.com/pypa/setuptools_scm) to determine the package version from the release tag (this is quite handy after you get used to it)

**Comment by Drfengze** [comment]
The same question, I reinstalled my anaconda but it didn't work, what should I do to use an older version?

**Comment by thouska** [comment]
sorry for that, I am on it, for now you can downgrade by using `pip install spotpy==1.5.10`.
I will keep you updated here as soon as the error is fixed.

**Comment by thouska** [comment]
Ok, the issue should be fixed now. 
Feel free to test spotpy version 1.5.13 on pypi.

**Comment by thouska** [comment]
@MuellerSeb I will look into it. Especially the automatic version control sounds interessting. I will try to implement it. Thx for the tip! 
The autmoatic deployment via Travis seems to work now :) It does not test it on test-pypi before, which as already proven to be not a good idea, but I think this was just me not using the script corectly... However, if problems persits to arise with that I will test the way you are using it in your great Geostat-Framework tools.

**Comment by MuellerSeb** [comment]
Nice!

**Comment by thouska** [comment]
Ok nice, seems to work now, thx again for reporting :)
