### ISSUE TITLE
likelihoods.py, generalizedLikelihoodFunction residuals not computed correctly

### ISSUE THREAD

**Issue by jds485** [thouska/spotpy#257]
The residuals should be with respect to the scaled (bias-corrected) value (E in Schoups and Vrugt, 2010, Eq. 1). They are currently computed with respect to the unscaled value (Y_h in Schoups and Vrugt, 2010, Eq. 2) using the __calcSimpleDeviation function.

A new function is needed, similar to the following:
def __calcSimpleDeviation_bias(data, comparedata, mu_h):
    __standartChecksBeforeStart(data, comparedata)
    d = np.array(data)
    c = np.array(comparedata)
    #Adjust c for multiplicative bias parameter:
    mu_t = np.exp(mu_h * c)
    Et = c * mu_t
    return d - Et

The function is called in [Line 432](https://github.com/thouska/spotpy/blob/master/spotpy/likelihoods.py#L432).

**Comment by thouska** [comment]
Hi @jds485 
thank you for your bugreport and the provided solution! I included your suggested fix. This will be available in spotpy version >=1.5.14
