### ISSUE TITLE
What is the `Load_Data` from `Hydrological_model.md`?

### ISSUE THREAD

**Issue by kaionwong** [thouska/spotpy#259]
Hi, I am unable to locate what `Load_Data` from your A hydrological model example (https://spotpy.readthedocs.io/en/latest/Hydrological_model/ , or Hydrological_model.md) refers to. Please advise.

**Comment by thouska** [comment]
The `Load data` section is not compatible with the [MIT license](https://github.com/thouska/spotpy/blob/master/LICENSE) of spotpy, therefor it was never published. As this makes the example not reproduceable, I decided to remove it from the documentation. Thank you for reminding me of that. Relevant parts are now introduced in a more general [example](https://spotpy.readthedocs.io/en/latest/Calibrating%20a%20hydrological%20model%20with%20DREAM/).

**Comment by kaionwong** [comment]
Thanks, I will close this issue.
