### ISSUE TITLE
Is the FAST sampler not compatible with the parameter type list?

### ISSUE THREAD

**Issue by TheodorB** [thouska/spotpy#265]
So I get this error when running the FAST algorithm:

   **_raise ValueError("Bounds are not legal")
ValueError: Bounds are not legal_**

and parameters generated are these:

[(nan, 'Ks', 0., 0., 0., 0., False) (nan, 'Alpha', 0., 0., 0., 0., False)
 (nan, 'n', 0., 0., 0., 0., False) (nan, 'P2H', 0., 0., 0., 0., False)
 (nan, 'P2L', 0., 0., 0., 0., False)
 (nan, 'rootDepth', 0., 0., 0., 0., False)
 (nan, 'C50', 0., 0., 0., 0., False)
 (nan, 'rain_err', 0., 0., 0., 0., False)
 (nan, 'thetar', 0., 0., 0., 0., False)
 (nan, 'thetas', 0., 0., 0., 0., False)
 (nan, 'thetai', 0., 0., 0., 0., False)
 (nan, 'etp_err', 0., 0., 0., 0., False)]

Although I definitely passed a list of values.

### Is the FAST sampler not compatible with the parameter type list?
Is there a work-around it?

**Comment by thouska** [comment]
this was discussed via pm. 
In case one comes accross this: It is not possible to use the fast sampler with a given parameter list. In fact spotpy.parameter.list is designed to work with Monte Carlo sampler only.
