### ISSUE TITLE
Long parameter names get truncated

### ISSUE THREAD

**Issue by joAschauer** [thouska/spotpy#269]
Hi there,
thanks for the great package. I am calibrating a model with somewhat long parameter names and spotpy truncates the names internally. This is a bit annoying when the found parameters are intended to be used later on or when parameter names are referenced in the ´simulation()´ method of the Setup class.

The truncation is defined here: https://github.com/thouska/spotpy/blob/9c454e8858ebda267255f8dbb4bc00019fec437b/spotpy/parameter.py#L682

Is there any reasoning why you introduced the 30 character limit?

**Comment by thouska** [comment]
Hi @joAschauer ,
thank you for this error report. You are right, there was no particular reason, to introduce this 30 character limit. Which limit would suit you? I can publish a new version accordingly.

**Comment by joAschauer** [comment]
Hello @thouska, 
thanks for your reply. I don't know which limit would be suitable... You could go for a 100 character limit which I'd assume should suffice for most people.

**Comment by thouska** [comment]
100 characters sounds like a good suggestion, I changed the values accordingly.
As the database saved values with a resolution of np.float16 by default, I also increased that setting to np.float32. This should, hopefully, prevent most errors, which are related to truncation of data.
