### ISSUE TITLE
Array evaluation error when using objective function rmse

### ISSUE THREAD

**Issue by zutn** [thouska/spotpy#27]
When using spotpy.objectivefunciton.rmse in python 3.5 following error is raised:
"The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

This happens because the array with the evaluation data is handled in a boolean context without specification if it should be true if all values are true or if it should be true if at leat one value is true. 

I would propose to use evaluation.all() to solve this problem

**Comment by gitporst** [comment]
Did you try it with the most recent version from the master branch? This problem should be solved by #25. 
evaluation.all() would only work for objects with an all() method, so this will for example not cover scalars...
