### ISSUE TITLE
pandas not listed as required dependency

### ISSUE THREAD

**Issue by arthur-e** [thouska/spotpy#272]
I was dismayed to discover, after a long-running sampling, that `pandas` is a required dependency for `spotpy.analyser.plot_parameterInteraction()`. This should be listed in the `setup.cfg` or `setup.py` files so that it is installed when `spotpy` is installed.

```
Traceback (most recent call last):
...
  File "/home/arthur.endsley/python-env/smap-l4c/lib/python3.7/site-packages/spotpy/analyser.py", line 939, in plot_parameterInteraction
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

**Comment by thouska** [comment]
Added as proposed
