### ISSUE TITLE
datawriter creation wastes a serial model run

### ISSUE THREAD

**Issue by philippkraft** [thouska/spotpy#28]
When the datawriter is created, a full model run is needed, just to get the size of the simulation. This behaviour is fine for fast models (run time<1 min) but for slow models, this is not acceptable. I see two options:
1. Use the evaluation to get the dimensions
1. A new parameter for the sampler where the user can give the size of the simulation (optional, if not given the model run is performed and the results are used for the dimension)

Any thoughts?

**Comment by thouska** [comment]
I think one possible way to deal with this, is to move the database initialization from _algorithm.py into the single algorithms. They know when they started the model for the first time and can call the database initialization before the saving routine is started. I uploaded some code that should solve the problem without significant performance loss (version >= 1.2.28, for testing purpose for now only on github). Anyone with a fancier solution/idea is welcome to reopen this issue.
