### ISSUE TITLE
Parameter tuple with a constrain 

### ISSUE THREAD

**Issue by lu-kas** [thouska/spotpy#280]
Dear all,

is it possible to create parameters as a tuple, which satisfies a given condition. E.g. n random numbers, which sum up to 1. Additionally, the elements of the random tuple have to be equally distributed.

Thanks!

Best,
Lukas

**Comment by thouska** [comment]
Hi Lukas,

it would be possible to generate your own parameter List, with the `spotpy.parameter.List` function. How it can be used is shown [here](https://github.com/thouska/spotpy/blob/master/spotpy/examples/tutorial_Parameterlist_iterator.py#L21).
You can put any numbers in that List that fullfill your conditions. If such an object is given, SPOTPY will not change these values, but go through them in the order of the given numbers. All other given parameter objects will change according to the selected algorithm.

**Comment by philippkraft** [comment]
Another possibility is to just create a bunch of uniform parameters in the [0..1] range and then normalize the parameters in the simulation method of your setup class.

~~~~~~~~~~.py
def simulation(self, x):
    x = x / np.sum(x)
    ...
~~~~~~~~~~~~~

**Comment by lu-kas** [comment]
Dear @philippkraft , dear @thouska 

thanks for your prompt answers and please excuse my very late response. We will have to try out your proposed suggestions. Regarding the proposed normalisation ( x=x/sum(x) ), I have hoped we could reduce the number of variables, as we have a given constrain, thus we could reduce the length of x from n to n-1.

I will close the issue for now.

Thanks for creating and actively maintaining this great tool! 

Best
Lukas
