### ISSUE TITLE
Test-PyPI upload failed

### ISSUE THREAD

**Issue by MuellerSeb** [thouska/spotpy#289]
See here: https://github.com/thouska/spotpy/runs/7356839694

It says:
```
Warning:  It looks like you are trying to use an API token to authenticate in the package index and your token value does not start with "pypi-" as it typically should. This may cause an authentication error. Please verify that you have copied your token properly if such an error occurs.
...
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
         Invalid or non-existent authentication information. See                
        [ https://test.pypi.org/help/#inv](https://test.pypi.org/help/#invalid-auth)alid-auth for more information.
```
@thouska, guess your token is maybe outdated or wrongly copied.

**Comment by thouska** [comment]
Hi @MuellerSeb, thank you for your report.

I tried several things directly on the master branch and it doesn't seem to solve the problem.

I double-checked/updated the Tokens from test.pypi, as well as their implementation on Github Secrets, according to the documentations [from pypi](https://test.pypi.org/help/#apitoken) and [github](https://github.com/marketplace/actions/pypi-publish) and followed the [error searching guidelines](https://test.pypi.org/help/#invalid-auth) with no success.

Could it be that I need to link my test.pypi account somehow to Github? Or is this handled by the Token? I am a bit puzzled here.

**Comment by thouska** [comment]
This is fixed now. Turns out there is a difference between "environment secrets" and "repository secrets" within GitHub :)
