### ISSUE TITLE
SCEUA Export of intermediate process parameters

### ISSUE THREAD

**Issue by dingxinjun** [thouska/spotpy#298]
when implent SCEUA algorism optimization hydrological pamameter  algorism,repetitions=10000.it means the model run 10000 times of randomly generated parameter dataset and finally find the best parameter. i want to export the intermediate process parameters.and the corresponding  NSE of each parameter set.how can i export all the result?

**Comment by thouska** [comment]
Hi @dingxinjun, unfortunately this functionality is not implemented in the sceua sampler in spotpy
