### ISSUE TITLE
Error using sceua

### ISSUE THREAD

**Issue by MuellerSeb** [thouska/spotpy#30]
Hey,

i get the following error using the sceua algorithm:
"File "/usr/local/lib/python2.7/dist-packages/spotpy/algorithms/sceua.py", line 332, in sample BESTX=BESTX.reshape(BESTX.size/self.nopt,self.nopt)
TypeError: 'float' object cannot be interpreted as an index

and that is maybe a consequence form the division import from __future__, that makes BESTX.size/self.nopt a float. Maybe it should be replaces with BESTX.size//self.nopt ?!

nevertheless great work!

**Comment by thouska** [comment]
Hi @MuellerSeb,
thank you for reporting this! I uploaded a fix like you proposed (BESTX.size//self.nopt).
