### ISSUE TITLE
Links to code in tutorials link to 404

### ISSUE THREAD

**Issue by florianjehn** [thouska/spotpy#300]
I looked at several tutorials:
[https://spotpy.readthedocs.io/en/latest/How_to_link_a_model_to_SPOTPY/](https://spotpy.readthedocs.io/en/latest/How_to_link_a_model_to_SPOTPY/)
[https://spotpy.readthedocs.io/en/latest/Sensitivity_analysis_with_FAST/](https://spotpy.readthedocs.io/en/latest/Sensitivity_analysis_with_FAST/)
[https://spotpy.readthedocs.io/en/latest/Calibration_with_SCE-UA/](https://spotpy.readthedocs.io/en/latest/Calibration_with_SCE-UA/)

For all of those the final sentence "The corresponding code is available for download here." links to 404.

**Comment by thouska** [comment]
Thanks @florianjehn for reporting this! Should be fixed now.
