### ISSUE TITLE
Having issues with the FAST algorithm?

### ISSUE THREAD

**Issue by porterma** [thouska/spotpy#42]
I am receiving the following error when I try to run the fast algorithm.

Creating FAST Matrix
Start sampling
Initialize database...
237 of 5000 (best like=-0.2818)
Duration:0.42 s
4999

                Error: Number of samples in model output file must be a multiple of D, 
                where D is the number of parameters in your parameter file.

My code is:
sampler = spotpy.algorithms.fast(setup, dbname='results/RosenFAST', dbformat='csv')
sampler.sample(rep)

I think it breaks when it gets into the analyze routine and tries to get data.

Any thoughts on the matter?

Thanks!

**Comment by p-lauer** [comment]
How many parameters do you have?
How many samples do you have?
How many samples are actually written to results/RosenFAST.csv?

**Comment by thouska** [comment]
I justed tested it and got an error at the end of the sampling, which is due to an change in the database functionality I made recent: 
` Error: Number of samples in model output file must be a multiple of D, 
                where D is the number of parameters in your parameter file.` 
I will upload a fix for that. Was that the problem?

**Comment by porterma** [comment]
I am simply following the Rosenbrock example and trying to reproduce those results. 

I have two parameters.
5000 samples
My output is attached.

The error is in this line of code: data = self.datawriter.getdata() in fast.py, which skips the first line of data in my output file.

[RosenFAST.txt](https://github.com/thouska/spotpy/files/1102197/RosenFAST.txt)
