### ISSUE TITLE
pypi version out of sync

### ISSUE THREAD

**Issue by Patrick-Lauer** [thouska/spotpy#5]
Hello!

The spotpy version in the pypi rep is not in sync with the github version. There is "from demc import demc" in algorithms/__init__.py while there is no demc in demc.py in the current pypi-version. Thus, spotpy fails to run out of the box when installed from the pypi rep.

Regards 

Patrick

**Comment by thouska** [comment]
Hey Patrick,
thank you for the notification! I removed the demc.py file and changed the init.py accordingly. 
spotpy should run now out of the box with version >=1.2.10. I will add the file again, as soon as it correctly works.
Kind regards,
Tobias

**Comment by Patrick-Lauer** [comment]
Hey Tobias,

thanks for your fast response.

Kind regards

Patrick
