### ISSUE TITLE
Plot function not working?

### ISSUE THREAD

**Issue by LLTommy** [thouska/spotpy#53]
Hi guys,
I just stumbled across this and played around a bit with it. I guess you are aware of it (is it just me?), but the plot functions don't seem to work. For example in the rosenbrock example (
https://github.com/thouska/spotpy/blob/master/spotpy/examples/tutorial_rosenbrock.py) example, you also commented the 'plot_parametertrace_algorithms' function at the of the file. I guess because it causes problems? Any plans of fixing this?

**Comment by thouska** [comment]
Hi LLTommy,
thanks for your bug report. There was one algorithm name missing in the rosenbrock example plot. I uploaded a fix for it.
The line is commented, because this example is used by travis-ci to test the package. When I checked last time, testing of plotting functionality was not possible.

**Comment by LLTommy** [comment]
Hey ya, 
I figured it out myself yesterday, it was simply something like passing sampler.getdata() into the function rather than append this to a list and then pass the list to the function (which then led to the error). So just a minor inconstancy. I will further test your model calibration suit and report when I see something. I have some ideas to potentially contribute as well, but I am not sure if I can find time to do that. Time is, as always, the big issue. Thanks in the meantime!

**Comment by thouska** [comment]
Hey, sounds good. Contributions are always warmly welcome! Looking foreward to hear from you.
