### ISSUE TITLE
Unexpected result using spotpy.analyser.get_best_parameterset on simple Rosenbrock fct optim output

### ISSUE THREAD

**Issue by jmp75** [thouska/spotpy#67]
Repro:

Environment py 3.6.3, used `pip3 install spotpy`, seems it resulted in spotpy version '1.3.13', one notch down from 1.3.14 on master as of writing.

```python
from spotpy.examples.spot_setup_rosenbrock import spot_setup
spot_setup=spot_setup()
rep=5000
sampler=spotpy.algorithms.sceua(spot_setup, dbname='RosenSCE', dbformat='ram')
sampler.sample(rep)
results = sampler.getdata()       
print(spotpy.analyser.get_best_parameterset(results))
```

the sampler outputs something sensible:

```
Best run at 4972 of 5000 (best like=-5.21633e-20) with parameter set:
[ 1.  1.]
```

however get_best_parameterset looks wrong (irrespective of maximize function argument)

```
print(spotpy.analyser.get_best_parameterset(results))
Best parameter set:
x=1126705.00841, y=1126705.00841
[( 1126705.00840722,  1126705.00840722)]
```

**Comment by thouska** [comment]
thank you for your bug report. I tested the current version of spotpy (1.3.14) with this and I was not able to reproduce this bug on python 3.6.3. If you or anyone else has this problem in the current version of spotpy, feel free to reopen this issue.
