### ISSUE TITLE
Log-Likelyhood sign

### ISSUE THREAD

**Issue by jcblemai** [thouska/spotpy#68]
Hi,

Thanks a lot for SPOTPY. I am working with it, and it's truly amazing. 

I'm writing you because I'm bugged by something concerning the log-likelihood.

The return value is:
` return -data.__len__()/2*np.log(2*np.pi) + np.nansum(np.log(measerror)) + 0.5*np.sum(((data-comparedata)/measerror)**2)`

Is it the expected behaviour here that the minus sign only applies to the first term ? Maybe I'm wrong but for me it should encompass all the formula,

Best regards,

Jo

**Comment by thouska** [comment]
Hi @jcblemai ,
many thanks for the bug report and for using SPOTPY. You are absolutly right, the minus sign should be applied for the whole formular, I uploaded a fix for that.

**Comment by jcblemai** [comment]
Perfect many thanks ! Have a wonderful weekend.
