### ISSUE TITLE
Pictures broken in tutorials

### ISSUE THREAD

**Issue by neothemachine** [thouska/spotpy#7]
The pictures seem to be broken in the tutorials, like http://fb09-pasig.umwelt.uni-giessen.de/spotpy/Tutorial/4-Ackley/ This links to http://fb09-pasig.umwelt.uni-giessen.de/spotpy/Tutorial/4-Ackley/img/ackleytracelike.png which returns 404?

**Comment by thouska** [comment]
thank you for reporting this! Should be fixed now.

**Comment by neothemachine** [comment]
Cool thanks!
