### ISSUE TITLE
alt_objfun does not exist for FAST 

### ISSUE THREAD

**Issue by ashishvinayak** [thouska/spotpy#75]
Hey there,

 I am playing around with the FAST algorithm since we are using **spotpy** in our own code. The alt_objfun method does not work in case of FAST. I would like to make this happen, and a few other things such as adding a breakpoint to restart simulations. Would you be open to having these issues resolved? 

Best regards,
Ashish

**Comment by thouska** [comment]
Hi Ashish,
thank you for your message. The alt_objfunc keyword is not nescessary for the fast algorithm as it is always jumping into your def objectivefunction.
Regarding to the breakpoint/restart thing: Should not be too complicated to get this implemented. I can have a look in the next days and will keep you updated.

**Comment by ashishvinayak** [comment]
Okay, I see it now. In case we create a spot_setup containing an 'def objective_function' and 2 object instances from spot_setup:
1. FAST will use the def objective_function
2. SCEUA will use the alt_objfunc (if provided) else fall back to def objective_function.

My initial understanding was that def objective_function will override alt_objfunc for sceua.

This is great! Thanks ! 

Side note: It would be nice to have the same consistency for both the algorithms but I leave that for your examination. :)

**Comment by thouska** [comment]
Good point, I will try to get the use of alt_objfunc more consitent. 
For now, I uploaded a first draft of the breakpoint setting stuff in FAST. Could you have a look, if it works as intended?

**Comment by ashishvinayak** [comment]
Great thanks! I'll look into it !

**Comment by ashishvinayak** [comment]
So it doesn't read the backup file. The reason for this is the read_breakdata function in _algorithm.py .

It would be more beneficial to simply return the entire pickle file and let the calling function decide how it wants to unpack it. (see commit d4828938861f442a7d7699ddf70c4499597828a3) It seems to have been changed again after that.  

So to sum up:

Optimisation algorithm packs data into 'work' variable -> makes call to write_breakdata(work) 

read_breakdata returns 'work' -> Optimization algorithm unpacks as required.

**Comment by ashishvinayak** [comment]
Seems to work now! Thank you !

**Comment by thouska** [comment]
Good point, I do not know why your commit of reading the pickle file chaged agian. I liked your version! I changed the code again

**Comment by thouska** [comment]
Ok great that the code is working now! Let me know if you find any further bugs.

**Comment by ashishvinayak** [comment]
Haha thanks! Anyway, one last suggestion for the weekend ;) Do you think it is beneficial to return the sensitivity indices from the `sample()` function in FAST like `return Si` ? 

It would serve 2 benefits- 
1. Si can be computed easily without a lot of overload (in a general case) However, setting up the object again to read data from file seems tedious because all the input parameters for `fast->analyse()` need to be computed again. 
2. It won't be needed to be computed again, and will save computational cost. We want to run sensitivity analysis on 35 parameters which means 84455 simulations minimum. I don't want to then have to run `fast -> analyse()` again if I could just save the data. ;)

Thanks for all the support ! Have a good weekend ! :)

**Comment by thouska** [comment]
Hi @ashishvinayak ,
thanks for your suggestion and sorry for my very late response. I implented your idea to return the Si values after the sampling of the fast algorithm. Now, it can be used like this:
`sampler=spotpy.algorithms.fast(spot_setup, dbname='FAST_hymod', dbformat='csv')`
`Si = sampler.sample(rep)`
