### ISSUE TITLE
Float Precision for csv Data Base File

### ISSUE THREAD

**Issue by TristanHehnen** [thouska/spotpy#77]
Hello, I'm using spotpy for inverse modelling, which involves some relatively large numbers (sometimes to the power of 20).  However, when spotpy creates the data base csv-file, those values are set to `inf`, which is slightly unfortunate.

It seems the issue is related to the lines: https://github.com/thouska/spotpy/blob/5091e2964039901a04eac1d4230c0a7e6927836b/spotpy/database.py#L200 and https://github.com/thouska/spotpy/blob/5091e2964039901a04eac1d4230c0a7e6927836b/spotpy/database.py#L206 in `database.py`. There, `np.float16` is chosen. Would it be possible to change it to a higher precision float, like `np.float64`, or maybe have this parameter accessable during the spotpy setup step for the users to choose?

**Comment by thouska** [comment]
Hi Tristan,
thank you for using SPOTPY and for your message. I like your idea of adding a new keyword for the database precision. This should now be possible:
`sampler = spotpy.algorithms.lhs(spot_setup(), dbname='highprecision', dbformat='csv', db_precision=np.float64)`

**Comment by TristanHehnen** [comment]
Oh wow, that was much faster than expected. Thank you very much!

I'll check it out asap.

**Comment by TristanHehnen** [comment]
Hi, so I checked it out and it works for me. 

Thank you very much!
