### ISSUE TITLE
ram DB is very slow on finalizing an otherwise small calibration problem.

### ISSUE THREAD

**Issue by jmp75** [thouska/spotpy#78]
While dealing with a use case where SCE-UA calibrates an external model, structurally not very different from the [hymod examples](https://github.com/thouska/spotpy/blob/master/spotpy/examples/spot_setup_hymod_python.py) but a simpler model, I found the runtime rather slow, and the end of the sampling getting stuck for minutes before finally returning. 

After debugging it seems that the ram DB is storing the data points of each simulation time series resulting. This is compounded by  numerous `np.transpose` in the `finalize` method of the class `ram`.

```python
    def save(self, objectivefunction, parameterlist, simulations=None,
             chains=1):
        self.ram.append(self.dim_dict['like'](objectivefunction) +
                        self.dim_dict['par'](parameterlist) +
                        self.dim_dict['simulation'](simulations) +
                        [chains])
```

if `simulations` is indeed expected to be an "array" (time series) in the case of hydrologic models, I am puzzled they would find their way by default into a calibration log.

Happy to contribute something, but I need clarifications as to the intentions of the design for the log databases.

**Comment by thouska** [comment]
Thanks for your message. You are right, it takes a while to transpose the list into an array format when using the `ram` database class. I think, this transposing was not really necessary. I uploaded a new version, where the `def finalize()` loops through the list without a `np.transpose` call. This should be faster. If you have any further ideas how to improve this, I am happy to hear your ideas. 
The design of the database is intended to return a structured numpy array for all different database classes `ram', `csv` and `sql`. The savest way is to return list(s) of values in the `def simulation()` but the database can also handle arrays. Time series objects would probably result in an error.

**Comment by jmp75** [comment]
Thank you - Indeed the runtime is much faster. I'll close this present issue, but more broadly I think the default behavior of algorithms should be not to include simulation data points in the log.
