### ISSUE TITLE
sample functions do not return anything

### ISSUE THREAD

**Issue by gitporst** [thouska/spotpy#8]
I am trying to work through the tutorial The Rosenbrock. When assembling the results, the outcomes of the sample methods are collected in the list as in
```
sampler=spotpy.algorithms.mc(spotpy_setup,    dbname='RosenMC',    dbformat='csv')
results.append(sampler.sample(rep))
```
However, only the sample methods in the algorithms classes sa, demcz and rope actually do return somehting (the variable data), so for the other algrotihms None is appended to results.

Maybe something like 
```
sampler=spotpy.algorithms.mc(spotpy_setup,    dbname='RosenMC',    dbformat='csv')
sampler.sample(rep)
results.append(sampler.getdata())
```

I am using Python 2.7.10 and spotpy 1.2.17

I see this is the way to go in the further tutorials, so my issue only refers to the documentation for The Rosenbrock then. :)

**Comment by gitporst** [comment]
I see this is the way to go in the further tutorials, so my issue only refers to the documentation for The Rosenbrock then. :)

**Comment by thouska** [comment]
thank you for the notfication! Have changed it for the Rosenbrock tutorial like you proposed.
