### ISSUE TITLE
stdev and mean not found in parameter.py classes

### ISSUE THREAD

**Issue by gitporst** [thouska/spotpy#9]
when initializing a parameter with say a Gamma distribution, the step and optguess attributes can't be set, because the variables mean and stdev are not found. I guess they are copy-paste-remainder form the Normal class. Setting a default value (optguess) for a Gamma distribution needs to be based on vars provided as arguments to the class init (shape in that case).

I will make a pull request for another structure of setting step and optguess. Tell me, what you think.

**Comment by thouska** [comment]
yupp, seams necessary, pull request would help.

**Comment by thouska** [comment]
ok I think this issue is solved with #13
