### ISSUE TITLE
Use of magic number "-99999" in bias objective function

### ISSUE THREAD

**Issue by havanagrawal** [thouska/spotpy#90]
There is a section in the `objectivefunction.py` file in the `bias` function:

```
if evaluation[i] == -99999:
    '''
    Cleans out No Data values
    '''
    logging.warning('Wrong Results! Clean out No Data Values')
    pass
```

I don't understand why this value of -99999 is being used. I couldn't find this number anywhere else in the repository, and similar functions (such as `pbias`) do not do this.

Perhaps I am missing a particular data point, but it looks like this check is redundant, and perhaps can be removed.

**Comment by thouska** [comment]
This is not necessary anymore and coul be replaced with a filter for all objectivefunctions as requested in #79

**Comment by thouska** [comment]
Solved
