### ISSUE TITLE
Error in the bias objective function

### ISSUE THREAD

**Issue by havanagrawal** [thouska/spotpy#94]
The formula for the bias of an estimator in the docstring is:

<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{1}{N}&space;\sum_{i=1}^{N}(e_{i}-s_{i})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{1}{N}&space;\sum_{i=1}^{N}(e_{i}-s_{i})" title="\frac{1}{N} \sum_{i=1}^{N}(e_{i}-s_{i})" /></a>

But the current implementation calculates the opposite:

[`bias_values.append(float(simulation[i]) - float(evaluation[i]))`](https://github.com/thouska/spotpy/blob/master/spotpy/objectivefunctions.py#L45)

I wonder if both the equations are missing an absolute sign, or one or the other is wrong.

**Comment by thouska** [comment]
Thank you very much for this hint! Indeed, there was in error. According to http://onlinelibrary.wiley.com/doi/10.1029/97WR03495/epdf it is like the doc string said, so the code was wrong. I uploaded a fix for that.

**Comment by thouska** [comment]
ok I think this solved now
