### ISSUE TITLE
Intermittent execution error in objectivefunction

### ISSUE THREAD

**Issue by ThibHlln** [thouska/spotpy#98]
I am running into issues with version 1.3.20 (that I was not able to reproduce in version 1.3.19 so far). I am using Python 2.7.13. The problem occurs when an objective function is called in objectivefunctions.py (I have had the problem with both nashsutcliffe() and rmse(), I have not tested other functions). I am using the LHS method for the sampling of the parameters. And I am not using parallelisation at the moment.

To isolate problems due to my hydrological model procedural implementation, I have used a fixed list of simulation values and a fixed list of evaluation values so that my model is not being used at all (the problem also happen when I convert the lists into numpy arrays). Although, the same problem happens when I am actually using my model.

When using one objective function, the error raised is that evaluation and simulation lengths are different However, it happens sporadically (see below). In a debugging session, I can see that the simulation list is passed to nashstucliffe as [NaN] when the warning on length is raised.
_Starting the LHS algotrithm with 10000 repetitions...
Creating LatinHyperCube Matrix
Initialize database...
121 of 10000 (best like=0.522644) est. time remaining: 00:02:42
249 of 10000 (best like=0.522644) est. time remaining: 00:02:36
377 of 10000 (best like=0.522644) est. time remaining: 00:02:33
505 of 10000 (best like=0.522644) est. time remaining: 00:02:30
633 of 10000 (best like=0.522644) est. time remaining: 00:02:28
761 of 10000 (best like=0.522644) est. time remaining: 00:02:25
889 of 10000 (best like=0.522644) est. time remaining: 00:02:23
1017 of 10000 (best like=0.522644) est. time remaining: 00:02:21
1144 of 10000 (best like=0.522644) est. time remaining: 00:02:19
1256 of 10000 (best like=0.522644) est. time remaining: 00:02:19
1384 of 10000 (best like=0.522644) est. time remaining: 00:02:17
1512 of 10000 (best like=0.522644) est. time remaining: 00:02:15
1640 of 10000 (best like=0.522644) est. time remaining: 00:02:12
1768 of 10000 (best like=0.522644) est. time remaining: 00:02:10
1896 of 10000 (best like=0.522644) est. time remaining: 00:02:08
2024 of 10000 (best like=0.522644) est. time remaining: 00:02:06
2152 of 10000 (best like=0.522644) est. time remaining: 00:02:04
2280 of 10000 (best like=0.522644) est. time remaining: 00:02:02
Traceback (most recent call last):
WARNING: objectivefunctions.nashsutcliffe(): evaluation and simulation lists does not have the same length.
  File "C:\Python27\13x64\Lib\multiprocessing\queues.py", line 264, in _feed
    send(obj)
IOError: [Errno 232] The pipe is being closed
2408 of 10000 (best like=0.522644) est. time remaining: 00:02:00
2536 of 10000 (best like=0.522644) est. time remaining: 00:01:58
2664 of 10000 (best like=0.522644) est. time remaining: 00:01:56
2792 of 10000 (best like=0.522644) est. time remaining: 00:01:54
2920 of 10000 (best like=0.522644) est. time remaining: 00:01:51
3048 of 10000 (best like=0.522644) est. time remaining: 00:01:49_

Another problem, still with objectivefunctions.py, happens when I am using two objective functions (one custom-made one in combination with nashsutcliffe). This time a float is passed to nashsutcliffe so that the len() function raises a TypeError (see below). Once again, the execution works for a number of iterations before ending with an error.
_Starting the LHS algotrithm with 1000 repetitions...
Creating LatinHyperCube Matrix
Initialize database...
127 of 1000 (best like=0.522644) est. time remaining: 00:00:14
255 of 1000 (best like=0.522644) est. time remaining: 00:00:12
383 of 1000 (best like=0.522644) est. time remaining: 00:00:10
Traceback (most recent call last):
  File "C:/PycharmProjects/Python/SMARTpy/scripts/SMARTpy_withSPOTPY.py", line 93, in <module>
    Traceback (most recent call last):
spotpy_instructions(args.catchment, args.sample_size, parallelisation)
  File "C:\Python27\13x64\Lib\multiprocessing\queues.py", line 264, in _feed
  File "C:/PycharmProjects/Python/SMARTpy/scripts/SMARTpy_withSPOTPY.py", line 65, in spotpy_instructions
    sampler.sample(sample_size)
  File "C:\PycharmProjects\Python\SMARTpy\venv\lib\site-packages\spotpy\algorithms\lhs.py", line 98, in sample
    self.postprocessing(rep, randompar, simulations)
  File "C:\PycharmProjects\Python\SMARTpy\venv\lib\site-packages\spotpy\algorithms\_algorithm.py", line 289, in postprocessing
    like = self.getfitness(simulation=simulation, params=randompar)
  File "C:\PycharmProjects\Python\SMARTpy\venv\lib\site-packages\spotpy\algorithms\_algorithm.py", line 316, in getfitness
    return self.objectivefunction(evaluation=self.evaluation, simulation=simulation)
  File "C:/PycharmProjects/Python/SMARTpy/scripts/SMARTpy_withSPOTPY.py", line 54, in objectivefunction
        send(obj)
obj1 = spotpy.objectivefunctions.nashsutcliffe(evaluation=evaluation[0], simulation=simulation[0])
IOError: [Errno 109] The pipe has been ended
  File "C:\PycharmProjects\Python\SMARTpy\venv\lib\site-packages\spotpy\objectivefunctions.py", line 100, in nashsutcliffe
    if len(evaluation) == len(simulation):
TypeError: object of type 'float' has no len()_

Below, I am attaching the code for the two cases (1 objective function and 2 objective functions). The scripts are stand-alone.
[test_1objfn.txt](https://github.com/thouska/spotpy/files/1673410/test_1objfn.txt)
[test_2obfns.txt](https://github.com/thouska/spotpy/files/1673408/test_2obfns.txt)

Is anyone able to reproduce the error?

**Comment by thouska** [comment]
Hi @ThibHlln 
thank you for your message and sorry for this inconvenience. I tested your two scripts with 10000 repetions each and was not able to reproduce the error.
However, I tested it with the latest version of SPOTPY (1.3.21, which is available since now on pypi) and which has has some rewritten objective function stuff (#91). This might have solved your issue. Would you mind to test your scripts again with this version?

**Comment by ThibHlln** [comment]
Hi @thouska 

Thank you very much for your quick answer. No worries, this is no inconvenience to me, I can use version 1.3.19 that works well for my use of SPOTPY. I just would like to contribute to SPOTPY at my own small level if I can. Thank you very much for developing SPOTPY, it is great to have such a toolbox in Python!

I have upgraded to 1.3.21 and I am still having the same issue. I don't know if you will ever be able to reproduce it on your machine, but maybe I should mention that it is not systematically happening. Sometimes I am able to go through a full iteration over 10000 samples without any problem. This is what is really disconcerting. Since each sample is using the exact same list of simulation and evaluation values, I would expect a consistent behaviour. 

Do not hesitate to let me know if there is anything else I can test to find a solution to the problem, if the problem is not only happening to me, that is.

**Comment by thouska** [comment]
ok thank you for your report. It is also possible that the problem is due to a timeout routine, which we have implemented in the SPOTPY version 1.3.20. This would be a Python 2 issue then. We will look into this and keep you updated.

**Comment by thouska** [comment]
Not sure, if @bees4ever fix #102 solves the problem. @ThibHlln would you like to test this?

**Comment by ThibHlln** [comment]
Thanks @thouska  and @bees4ever 

I am not able to reproduce the error anymore (on macOS and Windows). So, yes, I think this solved the problem. Thank you very much to both of you.
